impedance_config = {
    "translational_stiffness": 2000,
    "translational_damping": 89,
    "rotational_stiffness": 150,
    "rotational_damping": 7,
    "translational_Ki": 0,
    "translational_clip_x": 0.003,
    "translational_clip_y": 0.003,
    "translational_clip_z": 0.01,
    "translational_clip_neg_x": 0.003,
    "translational_clip_neg_y": 0.003,
    "translational_clip_neg_z": 0.01,
    "rotational_clip_x": 0.02,
    "rotational_clip_y": 0.02,
    "rotational_clip_z": 0.02,
    "rotational_clip_neg_x": 0.02,
    "rotational_clip_neg_y": 0.02,
    "rotational_clip_neg_z": 0.02,
    "rotational_Ki": 0,
}
