impedence_config = {
    "translational_stiffness": 3000,
    "translational_damping": 180,
    "rotational_stiffness": 150,
    "rotational_damping": 7,
    "translational_clip_neg_x": 0.002,
    "translational_clip_neg_y": 0.002,
    "translational_clip_neg_z": 0.003,
    "translational_clip_x": 0.0025,
    "translational_clip_y": 0.0015,
    "translational_clip_z": 0.002,
    "rotational_clip_neg_x": 0.025,
    "rotational_clip_neg_y": 0.007,
    "rotational_clip_neg_z": 0.01,
    "rotational_clip_x": 0.025,
    "rotational_clip_y": 0.007,
    "rotational_clip_z": 0.01,
    "translational_Ki": 0,
    "rotational_Ki": 0,
}
